### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jack828** [RedDuckss/URTube#2]
Hello 👋  I'd like to help out here, but i have a couple of questions:

 - do you mind if i refactor the code and add a linter?
 - what is the service you're posting data to [here](https://github.com/RedDuckss/URTube/blob/master/app/assets/js/script.js#L101)

**Comment by jonbarrow** [comment]
Hey there!

* Sure, why not. Go for it.
* It is a proxy server I setup to make all YouTube API requests for me. I have limited knowledge of the full YouTube API, and as such I am unaware what the full extent is that could be done if someone got my API key (for example, I don't know if a person could use my API key to interact with my account directly). Since this is an Electron app, it's EXTREMELY easy to decompile the source and steal the API key. This, obviously, is not ideal. So the app makes all requests to a proxy server (which has the key) and returns the search results.

**Comment by jonbarrow** [comment]
You might want to wait before making any edits though. I just finished testing some soundcloud functions and am now working on implementing some basic soundcloud support. So the source is going to change a lot soon.
